<?php
$files = [
'./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.3.musicxml',
'./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.1.musicxml',
'./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.2.musicxml',
'./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.4.musicxml',
'./Bach/040_bach_Fuge.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_890.Preludio_e_Fuga_21_in_Sib_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_873.Preludio_e_Fuga_4_in_Do_diesis_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_884.Preludio_e_Fuga_15_in_Sol_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_0.Preludio_e_Fuga_6_in_Re_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_a.Preludio_e_Fuga_3_in_Do_diesis_Maggiore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_876.Preludio_e_Fuga_7_in_Mib_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_888.Preludio_e_Fuga_19_in_La_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_871.Preludio_e_Fuga_2_in_Do_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_887.Preludio_e_Fuga_18_in_Lab_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_889.Preludio_e_Fuga_20_in_La_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_893.Preludio_e_Fuga_24_in_Si_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_879.Preludio_e_Fuga_10_in_Mi_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_885.Preludio_e_Fuga_16_in_Sol_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_a.Preludio_e_Fuga_6_in_Re_Minore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_877.Preludio_e_Fuga_8_in_Mib_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_883.Preludio_e_Fuga_14_in_Fa_diesis_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_892.Preludio_e_Fuga_23_in_Si_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_0.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_b.Preludio_e_Fuga_2_in_Do_Maggiore_(b).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_891.Preludio_e_Fuga_22_in_Sib_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_874.Preludio_e_Fuga_5_in_Re_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_878.Preludio_e_Fuga_9_in_Mi_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_882.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_881.Preludio_e_Fuga_12_in_Fa_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_0.Preludio_e_Fuga_1_in_Do_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_886.Preludio_e_Fuga_17_in_Lab_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_880.Preludio_e_Fuga_11_in_Fa_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_866.Preludio_e_Fuga_21_in_Sib_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_0.Preludio_e_Fuga_6_in_Re_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_868.Preludio_e_Fuga_23_in_Si_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_0.Preludio_e_Fuga_2_in_Do_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_0.Preludio_e_Fuga_5_in_Re_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_a.Preludio_e_Fuga_2_in_Do_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_a.Preludio_e_Fuga_10_in_Mi_Minore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_864.Preludio_e_Fuga_19_in_La_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_849.Preludio_e_Fuga_4_in_Do_diesis_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_0.Preludio_e_Fuga_10_in_Mi_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_848.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_853.Preludio_e_Fuga_8_in_Mib_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_859.Preludio_e_Fuga_14_in_Fa_diesis_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_a.Preludio_e_Fuga_5_in_Re_Maggiore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_a.Preludio_e_Fuga_6_in_Re_Minore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_854.Preludio_e_Fuga_9_in_Mi_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_861.Preludio_e_Fuga_16_in_Sol_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_865.Preludio_e_Fuga_20_in_La_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_860.Preludio_e_Fuga_15_in_Sol_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_0.Preludio_e_Fuga_1_in_Do_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.01.Preludio/Preludio_1_in_Do_Maggiore.musicxml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.02.Fuga/Fuga_1_in_Do_Maggiore.musicxml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_858.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_867.Preludio_e_Fuga_22_in_Sib_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_862.Preludio_e_Fuga_17_in_Lab_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_863.Preludio_e_Fuga_18_in_Lab_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_856.Preludio_e_Fuga_11_in_Fa_Maggiore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_857.Preludio_e_Fuga_12_in_Fa_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_869.Preludio_e_Fuga_24_in_Si_Minore.xml',
'./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_852.Preludio_e_Fuga_7_in_Mib_Maggiore.xml',
'./Bartók/Mikrokosmos/Volume_2/052.Monody_Divided.xml',
'./Bartók/Mikrokosmos/Volume_2/039.Staccato_and_Legato_(2,_Canon).xml',
'./Bartók/Mikrokosmos/Volume_2/050.Minuetto.xml',
'./Bartók/Mikrokosmos/Volume_2/042.Accompaniment_in_Broken_Triads.xml',
'./Bartók/Mikrokosmos/Volume_2/049.Crescendo_-_Diminuendo.xml',
'./Bartók/Mikrokosmos/Volume_2/041.Melody_with_Accompaniment.xml',
'./Bartók/Mikrokosmos/Volume_2/037.In_Lydian_Mode.xml',
'./Bartók/Mikrokosmos/Volume_2/063.Buzzing.xml',
'./Bartók/Mikrokosmos/Volume_2/046.Increasing_-_Diminishing.xml',
'./Bartók/Mikrokosmos/Volume_2/066.Melody_Divided.xml',
'./Bartók/Mikrokosmos/Volume_2/061.Pentatonic_Melody.xml',
'./Bartók/Mikrokosmos/Volume_2/058.In_Oriental_Style.xml',
'./Bartók/Mikrokosmos/Volume_2/040.In_Yugoslav_Style.xml',
'./Bartók/Mikrokosmos/Volume_2/064.Line_and_Point.xml',
'./Bartók/Mikrokosmos/Volume_2/059.Major_and_Minor.xml',
'./Bartók/Mikrokosmos/Volume_2/054.Chromatic.xml',
'./Bartók/Mikrokosmos/Volume_2/047.Big_Fair.xml',
'./Bartók/Mikrokosmos/Volume_2/056.Melody_in_Tenths.xml',
'./Bartók/Mikrokosmos/Volume_2/051.Waves.xml',
'./Bartók/Mikrokosmos/Volume_2/060.Canon_with_Sustained_Notes.xml',
'./Bartók/Mikrokosmos/Volume_2/038.Staccato_and_Legato_(1).xml',
'./Bartók/Mikrokosmos/Volume_2/053.In_Transylvanian_Style.xml',
'./Bartók/Mikrokosmos/Volume_2/048.In_Mixolydian_Mode.xml',
'./Bartók/Mikrokosmos/Volume_2/045.Méditation.xml',
'./Bartók/Mikrokosmos/Volume_2/062.Minor_Sixths_in_Parallel_Motion.xml',
'./Bartók/Mikrokosmos/Volume_2/057.Accents.xml',
'./Bartók/Mikrokosmos/Volume_4/118.Triplets_in_9∕8_Time.xml',
'./Bartók/Mikrokosmos/Volume_4/102.Harmonics.xml',
'./Bartók/Mikrokosmos/Volume_4/112.Variations_on_a_Folk_Tune.xml',
'./Bartók/Mikrokosmos/Volume_4/119.Dance_in_3∕4_Time.xml',
'./Bartók/Mikrokosmos/Volume_4/113.Bulgarian_Rhythm_(1).xml',
'./Bartók/Mikrokosmos/Volume_4/106.Childrenʼs_Song.xml',
'./Bartók/Mikrokosmos/Volume_4/114.Theme_and_Inversion.xml',
'./Bartók/Mikrokosmos/Volume_4/116.Melody.xml',
'./Bartók/Mikrokosmos/Volume_4/115.Bulgarian_Rhythm_(2).xml',
'./Bartók/Mikrokosmos/Volume_4/103.Minor_and_Major.xml',
'./Bartók/Mikrokosmos/Volume_4/098.Thumb_Under.xml',
'./Bartók/Mikrokosmos/Volume_4/107.Melody_in_the_Mist.xml',
'./Bartók/Mikrokosmos/Volume_4/111.Intermezzo.xml',
'./Bartók/Mikrokosmos/Volume_4/104.Wandering_through_the_Keys.xml',
'./Bartók/Mikrokosmos/Volume_4/101.Diminished_Fifths.xml',
'./Bartók/Mikrokosmos/Volume_4/120.Fifth_Chords.xml',
'./Bartók/Mikrokosmos/Volume_4/108.Wrestling.xml',
'./Bartók/Mikrokosmos/Volume_4/099.Crossed_Hands.xml',
'./Bartók/Mikrokosmos/Volume_4/121.Two-part_Study.xml',
'./Bartók/Mikrokosmos/Volume_4/109.From_the_Island_of_Bali.xml',
'./Bartók/Mikrokosmos/Volume_4/100.In_the_Style_of_a_Folksong.xml',
'./Bartók/Mikrokosmos/Volume_4/110.Clashing_Sounds.xml',
'./Bartók/Mikrokosmos/Volume_4/097.Notturno.xml',
'./Bartók/Mikrokosmos/Volume_4/105.Playsong_(with_two_pentatonic_scales).xml',
'./Bartók/Mikrokosmos/Volume_4/117.Bourée.xml',
'./Bartók/Mikrokosmos/Volume_3/096.Stumblings.xml',
'./Bartók/Mikrokosmos/Volume_3/072.Dragonsʼ_Dance.xml',
'./Bartók/Mikrokosmos/Volume_3/093.In_Four_Parts_(2).xml',
'./Bartók/Mikrokosmos/Volume_3/089.In_Four_Parts_(1).xml',
'./Bartók/Mikrokosmos/Volume_3/084.Merriment.xml',
'./Bartók/Mikrokosmos/Volume_3/085.Broken_Chords.xml',
'./Bartók/Mikrokosmos/Volume_3/090.In_Russian_Style.xml',
'./Bartók/Mikrokosmos/Volume_3/095.Song_of_the_Fox.xml',
'./Bartók/Mikrokosmos/Volume_3/088.Duet_for_Pipes.xml',
'./Bartók/Mikrokosmos/Volume_3/087.Variations.xml',
'./Bartók/Mikrokosmos/Volume_3/067.Thirds_against_a_Single_Voice.xml',
'./Bartók/Mikrokosmos/Volume_3/082.Scherzo.xml',
'./Bartók/Mikrokosmos/Volume_3/079.Hommage_à_J._S._B..xml',
'./Bartók/Mikrokosmos/Volume_3/075.Triplets.xml',
'./Bartók/Mikrokosmos/Volume_3/081.Wandering.xml',
'./Bartók/Mikrokosmos/Volume_3/073.Sixths_and_Triads.xml',
'./Bartók/Mikrokosmos/Volume_3/069.Chord_Study.xml',
'./Bartók/Mikrokosmos/Volume_3/078.Five-tone_Scale.xml',
'./Bartók/Mikrokosmos/Volume_3/092.Chromatic_Invention_(2).xml',
'./Bartók/Mikrokosmos/Volume_3/091.Chromatic_Invention_(1).xml',
'./Bartók/Mikrokosmos/Volume_3/094.Tale.xml',
'./Bartók/Mikrokosmos/Volume_3/077.Little_Study.xml',
'./Bartók/Mikrokosmos/Volume_3/071.Thirds.xml',
'./Bartók/Mikrokosmos/Volume_3/086.Two_Major_Pentachords.xml',
'./Bartók/Mikrokosmos/Volume_3/080.Hommage_à_R._Sch..xml',
'./Bartók/Mikrokosmos/Volume_3/074.Hungarian_Song.xml',
'./Bartók/Mikrokosmos/Volume_3/083.Melody_with_Interruptions.xml',
'./Bartók/Mikrokosmos/Volume_3/070.Melody_against_Double_Notes.xml',
'./Bartók/Mikrokosmos/Volume_3/076.In_Three_Parts.xml',
'./Bartók/Mikrokosmos/Volume_1/010.With_Alternate_Hands.xml',
'./Bartók/Mikrokosmos/Volume_1/002.Six_Unison_Melodies,_no._2.xml',
'./Bartók/Mikrokosmos/Volume_1/035.Chorale.xml',
'./Bartók/Mikrokosmos/Volume_1/032.In_Dorian_Mode.xml',
'./Bartók/Mikrokosmos/Volume_1/036.Free_Canon.xml',
'./Bartók/Mikrokosmos/Volume_1/013.Change_of_Position.xml',
'./Bartók/Mikrokosmos/Volume_1/024.Pastorale.xml',
'./Bartók/Mikrokosmos/Volume_1/027.Syncopation_(2).xml',
'./Bartók/Mikrokosmos/Volume_1/022.Imitation_and_Counterpoint.xml',
'./Bartók/Mikrokosmos/Volume_1/017.Contrary_Motion_(1).xml',
'./Bartók/Mikrokosmos/Volume_1/012.Reflection.xml',
'./Bartók/Mikrokosmos/Volume_1/028.Canon_at_the_Octave.xml',
'./Bartók/Mikrokosmos/Volume_1/031.Little_Dance_in_Canon_Form.xml',
'./Bartók/Mikrokosmos/Volume_1/018.Four_Unison_Melodies,_no._1.xml',
'./Bartók/Mikrokosmos/Volume_1/020.Four_Unison_Melodies,_no._3.xml',
'./Bartók/Mikrokosmos/Volume_1/016.Parallel_Motion_and_Change_of_Position.xml',
'./Bartók/Mikrokosmos/Volume_1/004.Six_Unison_Melodies,_no._4.xml',
'./Bartók/Mikrokosmos/Volume_1/019.Four_Unison_Melodies,_no._2.xml',
'./Bartók/Mikrokosmos/Volume_1/015.Village_Song.xml',
'./Bartók/Mikrokosmos/Volume_1/026.Repetition_(2).xml',
'./Bartók/Mikrokosmos/Volume_1/034.In_Phrygian_Mode.xml',
'./Bartók/Mikrokosmos/Volume_1/007.Dotted_Notes.xml',
'./Bartók/Mikrokosmos/Volume_1/023.Imitation_and_Inversion_(1).xml',
'./Bartók/Mikrokosmos/Volume_1/008.Repetition_(1).xml',
'./Bartók/Mikrokosmos/Volume_1/014.Question_and_Answer.xml',
'./Bartók/Mikrokosmos/Volume_1/003.Six_Unison_Melodies,_no._3.xml',
'./Bartók/Mikrokosmos/Volume_1/011.Parallel_Motion.xml',
'./Bartók/Mikrokosmos/Volume_1/030.Canon_at_the_Lower_Fifth.xml',
'./Bartók/Mikrokosmos/Volume_1/029.Imitation_Reflected.xml',
'./Bartók/Mikrokosmos/Volume_1/006.Six_Unison_Melodies,_no._6.xml',
'./Bartók/Mikrokosmos/Volume_1/001.Six_Unison_Melodies,_no._1.xml',
'./Bartók/Mikrokosmos/Volume_1/021.Four_Unison_Melodies,_no._4.xml',
'./Bartók/Mikrokosmos/Volume_1/033.Slow_Dance.xml',
'./Bartók/Mikrokosmos/Volume_1/009.Syncopation_(1).musicxml',
'./Bartók/Mikrokosmos/Volume_1/025.Imitation_and_Inversion_(2).xml',
'./Bartók/Mikrokosmos/Volume_1/005.Six_Unison_Melodies,_no._5.xml',
'./Bartók/Mikrokosmos/Volume_6/149.Six_Dances_in_Bulgarian_Rhythm,_No._2.xml',
'./Bartók/Mikrokosmos/Volume_6/148.Six_Dances_in_Bulgarian_Rhythm,_No._1.xml',
'./Bartók/Mikrokosmos/Volume_6/146.Ostinato.xml',
'./Bartók/Mikrokosmos/Volume_6/153.Six_Dances_in_Bulgarian_Rhythm,_No._6.xml',
'./Bartók/Mikrokosmos/Volume_6/144.Minor_Seconds,_Major_Sevenths.xml',
'./Bartók/Mikrokosmos/Volume_6/152.Six_Dances_in_Bulgarian_Rhythm,_No._5.xml',
'./Bartók/Mikrokosmos/Volume_6/151.Six_Dances_in_Bulgarian_Rhythm,_No._4.xml',
'./Bartók/Mikrokosmos/Volume_6/142.From_the_Diary_of_a_Fly.xml',
'./Bartók/Mikrokosmos/Volume_6/145.Chromatic_Invention_(3).xml',
'./Bartók/Mikrokosmos/Volume_6/140.Free_Variations.xml',
'./Bartók/Mikrokosmos/Volume_6/147.March.xml',
'./Bartók/Mikrokosmos/Volume_6/150.Six_Dances_in_Bulgarian_Rhythm,_No._3.xml',
'./Bartók/Mikrokosmos/Volume_6/141.Subject_and_Reflection.xml',
'./Bartók/Mikrokosmos/Volume_6/143.Divided_Arpeggios.xml',
'./Bartók/Mikrokosmos/Volume_5/137.Unison.xml',
'./Bartók/Mikrokosmos/Volume_5/133.Syncopation_(3).xml',
'./Bartók/Mikrokosmos/Volume_5/136.Whole-tone_Scale.xml',
'./Bartók/Mikrokosmos/Volume_5/130.Village_Joke.xml',
'./Bartók/Mikrokosmos/Volume_5/139.Merry_Andrew.xml',
'./Bartók/Mikrokosmos/Volume_5/129.Alternating_Thirds.xml',
'./Bartók/Mikrokosmos/Volume_5/124.Staccato.xml',
'./Bartók/Mikrokosmos/Volume_5/132.Major_Seconds_Broken_and_Together.xml',
'./Bartók/Mikrokosmos/Volume_5/125.Boating.xml',
'./Bartók/Mikrokosmos/Volume_5/138.Bagpipe.xml',
'./Bartók/Mikrokosmos/Volume_5/131.Fourths.xml',
'./Bartók/Mikrokosmos/Volume_5/126.Change_of_Time.xml',
'./Bartók/Mikrokosmos/Volume_5/123.Staccato_and_Legato_(3).xml',
'./Bartók/Mikrokosmos/Volume_5/134.Studies_in_Double_Notes.xml',
'./Bartók/Mikrokosmos/Volume_5/135.Perpetuum_mobile.xml',
'./Bartók/Mikrokosmos/Volume_5/122.Chords_Together_and_Opposed.xml',
'./Bartók/Mikrokosmos/Volume_5/128.Peasant_Dance.xml',
'./Hanon/Il_Pianista_Virtuoso/§.002_0.Esercizio_2.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.003_0.Esercizio_3.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.002_B.Esercizio_2_-_Sviluppo_B.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.001_0.Esercizio_1.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.001_B.Esercizio_1_-_Sviluppo_B.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.004_0.Esercizio_4.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.001_A.Esercizio_1_-_Sviluppo_A.musicxml',
'./Hanon/Il_Pianista_Virtuoso/§.002_A.Esercizio_2_-_Sviluppo_A.musicxml',
'./Chopin/Notturni/Waltz_in_A_Minor.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.017_1.Esercizio_17_(parti_invertite).musicxml',
'./Köhler/Il_Piccolo_Pianista/§.017_0.Esercizio_17_(originale).musicxml',
'./Köhler/Il_Piccolo_Pianista/§.016_0.Esercizio_16_(originale).musicxml',
'./Köhler/Il_Piccolo_Pianista/§.015.Esercizio_15.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.002.Esercizio_2.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.001.Esercizio_1.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.011.Esercizio_11.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.009.Esercizio_9.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.018.Esercizio_18.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.008.Esercizio_8.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.010.Esercizio_10.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.003.Esercizio_3.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.012.Esercizio_12.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.021.Esercizio_21.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.007.Esercizio_7.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.013.Esercizio_13.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.016_1.Esercizio_16_(parti_invertite).musicxml',
'./Köhler/Il_Piccolo_Pianista/§.019.Esercizio_19.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.014.Esercizio_14.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.004.Esercizio_4.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.005.Esercizio_5.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.006.Esercizio_6.musicxml',
'./Köhler/Il_Piccolo_Pianista/§.020.Esercizio_20.musicxml',
'./Test/Debug.musicxml',
'./Test/Stress_test_with_diminished_seventh_chords.musicxml',
'./Test/test-C.musicxml',
'./Test/Stress_Test_Key_Traspose.musicxml',
'./Test/ID-98013_Det_er_en_skatt_bak_dekker_gjemt.musicxml',
'./Test/test-C_diesis.musicxml',
'./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_2.musicxml',
'./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_1.musicxml',
'./Amedeo_Sorpreso/ci-manca.musicxml',
'./Amedeo_Sorpreso/Letture/Lettura_1.musicxml',
'./Satie/Gymnopdie_No._1__Satie.musicxml',
'./Morceau_pour_contrebasse_et_d_accompaniment_violoncelle_MS3.musicxml',
'./scores/pachelbel_canon.xml',
'./scores/bach_airgstring.xml',
'./scores/test_octaves.xml',
'./scores/couperin_baricades.xml',
'./scores/mozart_sonfacile.xml',
'./scores/bach_invention4.xml',
'./scores/bach_joy.xml',
'./scores/clayderman_ladyd.xml',
'./scores/test_scales.xml',
'./scores/test_chords.xml',
'./scores/bach_prelude.xml',
'./Beethoven/Beethoven_AnDieFerneGeliebte.xml',
];

$container_xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
."<container>\n"
."  <rootfiles>\n"
."    <rootfile full-path=\"score.xml\">\n"
."      </rootfile>\n"
."    </rootfiles>\n"
."  </container>\n";

$currentdir = getcwd();
$null= " 1>/dev/null 2>/dev/null";
$null="";
foreach($files as $xml) {
	$finfo = pathinfo($xml);
	$subdir = $finfo["dirname"]."/".$finfo["filename"];

  $command = "rm -Rf '${subdir}' ${null}";
	echo "${command}\n";
	exec($command);

  $command = "mkdir -p '${subdir}/META-INF' ${null}";
	echo "${command}\n";
	exec($command);

  file_put_contents("${subdir}/META-INF/container.xml",$container_xml);
	$command = "cp '$xml' '${subdir}/score.xml' ${null}";
	echo "${command}\n";
	exec($command);

  $mxl = $subdir.".mxl";

  $command = "rm '${mxl}' ${null}";
	echo "${command}\n";
	exec($command);

	$command ="cd '${subdir}' ${null}";
	echo "${command}\n";
	//exec($command);
  chdir($subdir);
  $command = "jar -M -c -f '../".$finfo["filename"].".mxl' . ${null}";
	echo "${command}\n";
	exec($command);

  $command ="cd '${currentdir}' ${null}";
	echo "${command}\n";
  chdir($currentdir);

  $command = "rm -Rf '${subdir}' ${null}";
	echo "${command}\n";
	exec($command);

  $command = "rm -Rf '${xml}' ${null}";
	echo "${command}\n";
	exec($command);

  //exec($command);
	echo "------------------------------------------------------------------------------------------\n";
}
/*
    [dirname] => ./scores
    [basename] => bach_prelude.xml
    [extension] => xml
    [filename] => bach_prelude
*/

./Chopin/Notturni/Waltz_in_A_Minor.mxl
./Köhler/Il_Piccolo_Pianista/§.017_1.Esercizio_17_(parti_invertite).mxl
./Köhler/Il_Piccolo_Pianista/§.021.Esercizio_21.mxl
./Köhler/Il_Piccolo_Pianista/§.018.Esercizio_18.mxl
./Köhler/Il_Piccolo_Pianista/§.002.Esercizio_2.mxl
./Köhler/Il_Piccolo_Pianista/§.017_0.Esercizio_17_(originale).mxl
./Köhler/Il_Piccolo_Pianista/§.016_1.Esercizio_16_(parti_invertite).mxl
./Köhler/Il_Piccolo_Pianista/§.008.Esercizio_8.mxl
./Köhler/Il_Piccolo_Pianista/§.014.Esercizio_14.mxl
./Köhler/Il_Piccolo_Pianista/§.011.Esercizio_11.mxl
./Köhler/Il_Piccolo_Pianista/§.012.Esercizio_12.mxl
./Köhler/Il_Piccolo_Pianista/§.010.Esercizio_10.mxl
./Köhler/Il_Piccolo_Pianista/§.016_0.Esercizio_16_(originale).mxl
./Köhler/Il_Piccolo_Pianista/§.003.Esercizio_3.mxl
./Köhler/Il_Piccolo_Pianista/§.020.Esercizio_20.mxl
./Köhler/Il_Piccolo_Pianista/§.004.Esercizio_4.mxl
./Köhler/Il_Piccolo_Pianista/§.006.Esercizio_6.mxl
./Köhler/Il_Piccolo_Pianista/§.015.Esercizio_15.mxl
./Köhler/Il_Piccolo_Pianista/§.009.Esercizio_9.mxl
./Köhler/Il_Piccolo_Pianista/§.001.Esercizio_1.mxl
./Köhler/Il_Piccolo_Pianista/§.005.Esercizio_5.mxl
./Köhler/Il_Piccolo_Pianista/§.019.Esercizio_19.mxl
./Köhler/Il_Piccolo_Pianista/§.013.Esercizio_13.mxl
./Köhler/Il_Piccolo_Pianista/§.007.Esercizio_7.mxl
./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.2.mxl
./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.4.mxl
./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.3.mxl
./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.1.mxl
./Hanon/Il_Pianista_Virtuoso/§.002_A.Esercizio_2_-_Sviluppo_A.mxl
./Hanon/Il_Pianista_Virtuoso/§.001_B.Esercizio_1_-_Sviluppo_B.mxl
./Hanon/Il_Pianista_Virtuoso/§.001_0.Esercizio_1.mxl
./Hanon/Il_Pianista_Virtuoso/§.001_A.Esercizio_1_-_Sviluppo_A.mxl
./Hanon/Il_Pianista_Virtuoso/§.003_0.Esercizio_3.mxl
./Hanon/Il_Pianista_Virtuoso/§.002_B.Esercizio_2_-_Sviluppo_B.mxl
./Hanon/Il_Pianista_Virtuoso/§.004_0.Esercizio_4.mxl
./Hanon/Il_Pianista_Virtuoso/§.002_0.Esercizio_2.mxl
./Morceau_pour_contrebasse_et_d_accompaniment_violoncelle_MS3.mxl
./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_2.mxl
./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_1.mxl
./Amedeo_Sorpreso/Letture/Lettura_1.mxl
./Amedeo_Sorpreso/ci-manca.mxl
./Satie/Gymnopdie_No._1__Satie.mxl
./Beethoven/Beethoven_AnDieFerneGeliebte.mxl
./scores/bach_invention4.mxl
./scores/test_scales.mxl
./scores/couperin_baricades.mxl
./scores/bach_prelude.mxl
./scores/clayderman_ladyd.mxl
./scores/bach_airgstring.mxl
./scores/pachelbel_canon.mxl
./scores/test_octaves.mxl
./scores/bach_joy.mxl
./scores/mozart_sonfacile.mxl
./scores/test_chords.mxl
./Test/Debug.mxl
./Test/Stress_Test_Key_Traspose.mxl
./Test/ID-98013_Det_er_en_skatt_bak_dekker_gjemt.mxl
./Test/Stress_test_with_diminished_seventh_chords.mxl
./Test/test-C.mxl
./Test/test-C_diesis.mxl
./Bach/040_bach_Fuge.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_0.Preludio_e_Fuga_1_in_Do_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_888.Preludio_e_Fuga_19_in_La_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_a.Preludio_e_Fuga_6_in_Re_Minore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_883.Preludio_e_Fuga_14_in_Fa_diesis_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_884.Preludio_e_Fuga_15_in_Sol_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_885.Preludio_e_Fuga_16_in_Sol_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_871.Preludio_e_Fuga_2_in_Do_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_874.Preludio_e_Fuga_5_in_Re_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_880.Preludio_e_Fuga_11_in_Fa_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_878.Preludio_e_Fuga_9_in_Mi_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_b.Preludio_e_Fuga_2_in_Do_Maggiore_(b).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_889.Preludio_e_Fuga_20_in_La_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_890.Preludio_e_Fuga_21_in_Sib_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_886.Preludio_e_Fuga_17_in_Lab_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_876.Preludio_e_Fuga_7_in_Mib_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_877.Preludio_e_Fuga_8_in_Mib_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_0.Preludio_e_Fuga_6_in_Re_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_881.Preludio_e_Fuga_12_in_Fa_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_887.Preludio_e_Fuga_18_in_Lab_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_891.Preludio_e_Fuga_22_in_Sib_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_879.Preludio_e_Fuga_10_in_Mi_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_892.Preludio_e_Fuga_23_in_Si_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_873.Preludio_e_Fuga_4_in_Do_diesis_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_a.Preludio_e_Fuga_3_in_Do_diesis_Maggiore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_882.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_893.Preludio_e_Fuga_24_in_Si_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_0.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_a.Preludio_e_Fuga_5_in_Re_Maggiore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_a.Preludio_e_Fuga_6_in_Re_Minore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_0.Preludio_e_Fuga_6_in_Re_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_a.Preludio_e_Fuga_10_in_Mi_Minore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_860.Preludio_e_Fuga_15_in_Sol_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_849.Preludio_e_Fuga_4_in_Do_diesis_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_862.Preludio_e_Fuga_17_in_Lab_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_861.Preludio_e_Fuga_16_in_Sol_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_848.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_a.Preludio_e_Fuga_2_in_Do_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_869.Preludio_e_Fuga_24_in_Si_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_0.Preludio_e_Fuga_5_in_Re_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_865.Preludio_e_Fuga_20_in_La_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.02.Fuga/Fuga_1_in_Do_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.01.Preludio/Preludio_1_in_Do_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_0.Preludio_e_Fuga_1_in_Do_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_854.Preludio_e_Fuga_9_in_Mi_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_856.Preludio_e_Fuga_11_in_Fa_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_857.Preludio_e_Fuga_12_in_Fa_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_867.Preludio_e_Fuga_22_in_Sib_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_863.Preludio_e_Fuga_18_in_Lab_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_852.Preludio_e_Fuga_7_in_Mib_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_853.Preludio_e_Fuga_8_in_Mib_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_868.Preludio_e_Fuga_23_in_Si_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_0.Preludio_e_Fuga_2_in_Do_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_858.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_0.Preludio_e_Fuga_10_in_Mi_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_859.Preludio_e_Fuga_14_in_Fa_diesis_Minore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_866.Preludio_e_Fuga_21_in_Sib_Maggiore.mxl
./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_864.Preludio_e_Fuga_19_in_La_Maggiore.mxl
./Bartók/Mikrokosmos/Volume_1/014.Question_and_Answer.mxl
./Bartók/Mikrokosmos/Volume_1/023.Imitation_and_Inversion_(1).mxl
./Bartók/Mikrokosmos/Volume_1/029.Imitation_Reflected.mxl
./Bartók/Mikrokosmos/Volume_1/028.Canon_at_the_Octave.mxl
./Bartók/Mikrokosmos/Volume_1/020.Four_Unison_Melodies,_no._3.mxl
./Bartók/Mikrokosmos/Volume_1/019.Four_Unison_Melodies,_no._2.mxl
./Bartók/Mikrokosmos/Volume_1/006.Six_Unison_Melodies,_no._6.mxl
./Bartók/Mikrokosmos/Volume_1/012.Reflection.mxl
./Bartók/Mikrokosmos/Volume_1/032.In_Dorian_Mode.mxl
./Bartók/Mikrokosmos/Volume_1/003.Six_Unison_Melodies,_no._3.mxl
./Bartók/Mikrokosmos/Volume_1/027.Syncopation_(2).mxl
./Bartók/Mikrokosmos/Volume_1/015.Village_Song.mxl
./Bartók/Mikrokosmos/Volume_1/024.Pastorale.mxl
./Bartók/Mikrokosmos/Volume_1/022.Imitation_and_Counterpoint.mxl
./Bartók/Mikrokosmos/Volume_1/030.Canon_at_the_Lower_Fifth.mxl
./Bartók/Mikrokosmos/Volume_1/004.Six_Unison_Melodies,_no._4.mxl
./Bartók/Mikrokosmos/Volume_1/001.Six_Unison_Melodies,_no._1.mxl
./Bartók/Mikrokosmos/Volume_1/002.Six_Unison_Melodies,_no._2.mxl
./Bartók/Mikrokosmos/Volume_1/013.Change_of_Position.mxl
./Bartók/Mikrokosmos/Volume_1/033.Slow_Dance.mxl
./Bartók/Mikrokosmos/Volume_1/016.Parallel_Motion_and_Change_of_Position.mxl
./Bartók/Mikrokosmos/Volume_1/025.Imitation_and_Inversion_(2).mxl
./Bartók/Mikrokosmos/Volume_1/035.Chorale.mxl
./Bartók/Mikrokosmos/Volume_1/026.Repetition_(2).mxl
./Bartók/Mikrokosmos/Volume_1/005.Six_Unison_Melodies,_no._5.mxl
./Bartók/Mikrokosmos/Volume_1/007.Dotted_Notes.mxl
./Bartók/Mikrokosmos/Volume_1/021.Four_Unison_Melodies,_no._4.mxl
./Bartók/Mikrokosmos/Volume_1/010.With_Alternate_Hands.mxl
./Bartók/Mikrokosmos/Volume_1/008.Repetition_(1).mxl
./Bartók/Mikrokosmos/Volume_1/018.Four_Unison_Melodies,_no._1.mxl
./Bartók/Mikrokosmos/Volume_1/031.Little_Dance_in_Canon_Form.mxl
./Bartók/Mikrokosmos/Volume_1/011.Parallel_Motion.mxl
./Bartók/Mikrokosmos/Volume_1/009.Syncopation_(1).mxl
./Bartók/Mikrokosmos/Volume_1/036.Free_Canon.mxl
./Bartók/Mikrokosmos/Volume_1/034.In_Phrygian_Mode.mxl
./Bartók/Mikrokosmos/Volume_1/017.Contrary_Motion_(1).mxl
./Bartók/Mikrokosmos/Volume_5/123.Staccato_and_Legato_(3).mxl
./Bartók/Mikrokosmos/Volume_5/125.Boating.mxl
./Bartók/Mikrokosmos/Volume_5/124.Staccato.mxl
./Bartók/Mikrokosmos/Volume_5/139.Merry_Andrew.mxl
./Bartók/Mikrokosmos/Volume_5/133.Syncopation_(3).mxl
./Bartók/Mikrokosmos/Volume_5/135.Perpetuum_mobile.mxl
./Bartók/Mikrokosmos/Volume_5/128.Peasant_Dance.mxl
./Bartók/Mikrokosmos/Volume_5/134.Studies_in_Double_Notes.mxl
./Bartók/Mikrokosmos/Volume_5/130.Village_Joke.mxl
./Bartók/Mikrokosmos/Volume_5/132.Major_Seconds_Broken_and_Together.mxl
./Bartók/Mikrokosmos/Volume_5/138.Bagpipe.mxl
./Bartók/Mikrokosmos/Volume_5/136.Whole-tone_Scale.mxl
./Bartók/Mikrokosmos/Volume_5/122.Chords_Together_and_Opposed.mxl
./Bartók/Mikrokosmos/Volume_5/131.Fourths.mxl
./Bartók/Mikrokosmos/Volume_5/126.Change_of_Time.mxl
./Bartók/Mikrokosmos/Volume_5/129.Alternating_Thirds.mxl
./Bartók/Mikrokosmos/Volume_5/137.Unison.mxl
./Bartók/Mikrokosmos/Volume_6/143.Divided_Arpeggios.mxl
./Bartók/Mikrokosmos/Volume_6/146.Ostinato.mxl
./Bartók/Mikrokosmos/Volume_6/149.Six_Dances_in_Bulgarian_Rhythm,_No._2.mxl
./Bartók/Mikrokosmos/Volume_6/148.Six_Dances_in_Bulgarian_Rhythm,_No._1.mxl
./Bartók/Mikrokosmos/Volume_6/150.Six_Dances_in_Bulgarian_Rhythm,_No._3.mxl
./Bartók/Mikrokosmos/Volume_6/141.Subject_and_Reflection.mxl
./Bartók/Mikrokosmos/Volume_6/153.Six_Dances_in_Bulgarian_Rhythm,_No._6.mxl
./Bartók/Mikrokosmos/Volume_6/144.Minor_Seconds,_Major_Sevenths.mxl
./Bartók/Mikrokosmos/Volume_6/142.From_the_Diary_of_a_Fly.mxl
./Bartók/Mikrokosmos/Volume_6/145.Chromatic_Invention_(3).mxl
./Bartók/Mikrokosmos/Volume_6/140.Free_Variations.mxl
./Bartók/Mikrokosmos/Volume_6/152.Six_Dances_in_Bulgarian_Rhythm,_No._5.mxl
./Bartók/Mikrokosmos/Volume_6/147.March.mxl
./Bartók/Mikrokosmos/Volume_6/151.Six_Dances_in_Bulgarian_Rhythm,_No._4.mxl
./Bartók/Mikrokosmos/Volume_2/063.Buzzing.mxl
./Bartók/Mikrokosmos/Volume_2/045.Méditation.mxl
./Bartók/Mikrokosmos/Volume_2/062.Minor_Sixths_in_Parallel_Motion.mxl
./Bartók/Mikrokosmos/Volume_2/048.In_Mixolydian_Mode.mxl
./Bartók/Mikrokosmos/Volume_2/046.Increasing_-_Diminishing.mxl
./Bartók/Mikrokosmos/Volume_2/050.Minuetto.mxl
./Bartók/Mikrokosmos/Volume_2/064.Line_and_Point.mxl
./Bartók/Mikrokosmos/Volume_2/040.In_Yugoslav_Style.mxl
./Bartók/Mikrokosmos/Volume_2/038.Staccato_and_Legato_(1).mxl
./Bartók/Mikrokosmos/Volume_2/054.Chromatic.mxl
./Bartók/Mikrokosmos/Volume_2/037.In_Lydian_Mode.mxl
./Bartók/Mikrokosmos/Volume_2/060.Canon_with_Sustained_Notes.mxl
./Bartók/Mikrokosmos/Volume_2/066.Melody_Divided.mxl
./Bartók/Mikrokosmos/Volume_2/056.Melody_in_Tenths.mxl
./Bartók/Mikrokosmos/Volume_2/058.In_Oriental_Style.mxl
./Bartók/Mikrokosmos/Volume_2/047.Big_Fair.mxl
./Bartók/Mikrokosmos/Volume_2/051.Waves.mxl
./Bartók/Mikrokosmos/Volume_2/049.Crescendo_-_Diminuendo.mxl
./Bartók/Mikrokosmos/Volume_2/053.In_Transylvanian_Style.mxl
./Bartók/Mikrokosmos/Volume_2/039.Staccato_and_Legato_(2,_Canon).mxl
./Bartók/Mikrokosmos/Volume_2/057.Accents.mxl
./Bartók/Mikrokosmos/Volume_2/041.Melody_with_Accompaniment.mxl
./Bartók/Mikrokosmos/Volume_2/059.Major_and_Minor.mxl
./Bartók/Mikrokosmos/Volume_2/061.Pentatonic_Melody.mxl
./Bartók/Mikrokosmos/Volume_2/042.Accompaniment_in_Broken_Triads.mxl
./Bartók/Mikrokosmos/Volume_2/052.Monody_Divided.mxl
./Bartók/Mikrokosmos/Volume_4/106.Childrenʼs_Song.mxl
./Bartók/Mikrokosmos/Volume_4/101.Diminished_Fifths.mxl
./Bartók/Mikrokosmos/Volume_4/112.Variations_on_a_Folk_Tune.mxl
./Bartók/Mikrokosmos/Volume_4/113.Bulgarian_Rhythm_(1).mxl
./Bartók/Mikrokosmos/Volume_4/119.Dance_in_3∕4_Time.mxl
./Bartók/Mikrokosmos/Volume_4/108.Wrestling.mxl
./Bartók/Mikrokosmos/Volume_4/114.Theme_and_Inversion.mxl
./Bartók/Mikrokosmos/Volume_4/097.Notturno.mxl
./Bartók/Mikrokosmos/Volume_4/121.Two-part_Study.mxl
./Bartók/Mikrokosmos/Volume_4/105.Playsong_(with_two_pentatonic_scales).mxl
./Bartók/Mikrokosmos/Volume_4/115.Bulgarian_Rhythm_(2).mxl
./Bartók/Mikrokosmos/Volume_4/109.From_the_Island_of_Bali.mxl
./Bartók/Mikrokosmos/Volume_4/116.Melody.mxl
./Bartók/Mikrokosmos/Volume_4/102.Harmonics.mxl
./Bartók/Mikrokosmos/Volume_4/107.Melody_in_the_Mist.mxl
./Bartók/Mikrokosmos/Volume_4/120.Fifth_Chords.mxl
./Bartók/Mikrokosmos/Volume_4/099.Crossed_Hands.mxl
./Bartók/Mikrokosmos/Volume_4/100.In_the_Style_of_a_Folksong.mxl
./Bartók/Mikrokosmos/Volume_4/110.Clashing_Sounds.mxl
./Bartók/Mikrokosmos/Volume_4/098.Thumb_Under.mxl
./Bartók/Mikrokosmos/Volume_4/111.Intermezzo.mxl
./Bartók/Mikrokosmos/Volume_4/117.Bourée.mxl
./Bartók/Mikrokosmos/Volume_4/118.Triplets_in_9∕8_Time.mxl
./Bartók/Mikrokosmos/Volume_4/104.Wandering_through_the_Keys.mxl
./Bartók/Mikrokosmos/Volume_4/103.Minor_and_Major.mxl
./Bartók/Mikrokosmos/Volume_3/091.Chromatic_Invention_(1).mxl
./Bartók/Mikrokosmos/Volume_3/087.Variations.mxl
./Bartók/Mikrokosmos/Volume_3/089.In_Four_Parts_(1).mxl
./Bartók/Mikrokosmos/Volume_3/093.In_Four_Parts_(2).mxl
./Bartók/Mikrokosmos/Volume_3/070.Melody_against_Double_Notes.mxl
./Bartók/Mikrokosmos/Volume_3/096.Stumblings.mxl
./Bartók/Mikrokosmos/Volume_3/069.Chord_Study.mxl
./Bartók/Mikrokosmos/Volume_3/092.Chromatic_Invention_(2).mxl
./Bartók/Mikrokosmos/Volume_3/088.Duet_for_Pipes.mxl
./Bartók/Mikrokosmos/Volume_3/083.Melody_with_Interruptions.mxl
./Bartók/Mikrokosmos/Volume_3/090.In_Russian_Style.mxl
./Bartók/Mikrokosmos/Volume_3/072.Dragonsʼ_Dance.mxl
./Bartók/Mikrokosmos/Volume_3/076.In_Three_Parts.mxl
./Bartók/Mikrokosmos/Volume_3/067.Thirds_against_a_Single_Voice.mxl
./Bartók/Mikrokosmos/Volume_3/071.Thirds.mxl
./Bartók/Mikrokosmos/Volume_3/074.Hungarian_Song.mxl
./Bartók/Mikrokosmos/Volume_3/078.Five-tone_Scale.mxl
./Bartók/Mikrokosmos/Volume_3/085.Broken_Chords.mxl
./Bartók/Mikrokosmos/Volume_3/082.Scherzo.mxl
./Bartók/Mikrokosmos/Volume_3/080.Hommage_à_R._Sch..mxl
./Bartók/Mikrokosmos/Volume_3/084.Merriment.mxl
./Bartók/Mikrokosmos/Volume_3/095.Song_of_the_Fox.mxl
./Bartók/Mikrokosmos/Volume_3/081.Wandering.mxl
./Bartók/Mikrokosmos/Volume_3/094.Tale.mxl
./Bartók/Mikrokosmos/Volume_3/075.Triplets.mxl
./Bartók/Mikrokosmos/Volume_3/077.Little_Study.mxl
./Bartók/Mikrokosmos/Volume_3/086.Two_Major_Pentachords.mxl
./Bartók/Mikrokosmos/Volume_3/073.Sixths_and_Triads.mxl
./Bartók/Mikrokosmos/Volume_3/079.Hommage_à_J._S._B..mxl
