<?php
$files = [
	"./Chopin/Notturni/Waltz_in_A_Minor.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.021.Esercizio_21.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.011.Esercizio_11.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.008.Esercizio_8.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.015.Esercizio_15.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.020.Esercizio_20.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.019.Esercizio_19.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.013.Esercizio_13.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.017_1.Esercizio_17_(parti_invertite).jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.006.Esercizio_6.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.004.Esercizio_4.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.009.Esercizio_9.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.001.Esercizio_1.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.003.Esercizio_3.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.002.Esercizio_2.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.012.Esercizio_12.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.016_1.Esercizio_16_(parti_invertite).jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.018.Esercizio_18.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.005.Esercizio_5.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.010.Esercizio_10.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.017_0.Esercizio_17_(originale).jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.007.Esercizio_7.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.014.Esercizio_14.jmxl/sheet.mxl",
	"./Köhler/Il_Piccolo_Pianista/§.016_0.Esercizio_16_(originale).jmxl/sheet.mxl",
	"./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.1.jmxl/sheet.mxl",
	"./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.2.jmxl/sheet.mxl",
	"./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.4.jmxl/sheet.mxl",
	"./Gleason/FGGleason_Four_Short_Compositions_for_Pianoforte_Op.8_No.3.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.003_0.Esercizio_3.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.002_A.Esercizio_2_-_Sviluppo_A.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.004_0.Esercizio_4.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.001_B.Esercizio_1_-_Sviluppo_B.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.001_A.Esercizio_1_-_Sviluppo_A.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.002_0.Esercizio_2.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.002_B.Esercizio_2_-_Sviluppo_B.jmxl/sheet.mxl",
	"./Hanon/Il_Pianista_Virtuoso/§.001_0.Esercizio_1.jmxl/sheet.mxl",
	"./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_1.jmxl/sheet.mxl",
	"./Amedeo_Sorpreso/Esercizi_5_Note/Esercizio_Indipendenza_2.jmxl/sheet.mxl",
	"./Amedeo_Sorpreso/Letture/Lettura_1.jmxl/sheet.mxl",
	"./Amedeo_Sorpreso/ci-manca.jmxl/sheet.mxl",
	"./Satie/Gymnopdie_No._1__Satie.jmxl/sheet.mxl",
	"./Beethoven/Beethoven_AnDieFerneGeliebte.jmxl/sheet.mxl",
	"./scores/bach_joy.jmxl/sheet.mxl",
	"./scores/couperin_baricades.jmxl/sheet.mxl",
	"./scores/mozart_sonfacile.jmxl/sheet.mxl",
	"./scores/bach_prelude.jmxl/sheet.mxl",
	"./scores/bach_airgstring.jmxl/sheet.mxl",
	"./scores/test_scales.jmxl/sheet.mxl",
	"./scores/test_chords.jmxl/sheet.mxl",
	"./scores/pachelbel_canon.jmxl/sheet.mxl",
	"./scores/test_octaves.jmxl/sheet.mxl",
	"./scores/bach_invention4.jmxl/sheet.mxl",
	"./scores/clayderman_ladyd.jmxl/sheet.mxl",
	"./Test/Debug.jmxl/sheet.mxl",
	"./Test/test-C_diesis.jmxl/sheet.mxl",
	"./Test/Stress_test_with_diminished_seventh_chords.jmxl/sheet.mxl",
	"./Test/ID-98013_Det_er_en_skatt_bak_dekker_gjemt.jmxl/sheet.mxl",
	"./Test/test-C.jmxl/sheet.mxl",
	"./Test/Stress_Test_Key_Traspose.jmxl/sheet.mxl",
	"./Bach/040_bach_Fuge.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_0.Preludio_e_Fuga_6_in_Re_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_887.Preludio_e_Fuga_18_in_Lab_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_882.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_891.Preludio_e_Fuga_22_in_Sib_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_871.Preludio_e_Fuga_2_in_Do_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_881.Preludio_e_Fuga_12_in_Fa_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_874.Preludio_e_Fuga_5_in_Re_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_888.Preludio_e_Fuga_19_in_La_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_0.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_884.Preludio_e_Fuga_15_in_Sol_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_890.Preludio_e_Fuga_21_in_Sib_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_889.Preludio_e_Fuga_20_in_La_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_873.Preludio_e_Fuga_4_in_Do_diesis_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_0.Preludio_e_Fuga_1_in_Do_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_885.Preludio_e_Fuga_16_in_Sol_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_893.Preludio_e_Fuga_24_in_Si_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_880.Preludio_e_Fuga_11_in_Fa_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_876.Preludio_e_Fuga_7_in_Mib_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_875_a.Preludio_e_Fuga_6_in_Re_Minore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_877.Preludio_e_Fuga_8_in_Mib_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_872_a.Preludio_e_Fuga_3_in_Do_diesis_Maggiore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_879.Preludio_e_Fuga_10_in_Mi_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_883.Preludio_e_Fuga_14_in_Fa_diesis_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_892.Preludio_e_Fuga_23_in_Si_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_878.Preludio_e_Fuga_9_in_Mi_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_886.Preludio_e_Fuga_17_in_Lab_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_2/§.BWV_870_b.Preludio_e_Fuga_2_in_Do_Maggiore_(b).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_a.Preludio_e_Fuga_10_in_Mi_Minore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_a.Preludio_e_Fuga_2_in_Do_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_860.Preludio_e_Fuga_15_in_Sol_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_853.Preludio_e_Fuga_8_in_Mib_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_868.Preludio_e_Fuga_23_in_Si_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_848.Preludio_e_Fuga_3_in_Do_diesis_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_861.Preludio_e_Fuga_16_in_Sol_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_867.Preludio_e_Fuga_22_in_Sib_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_a.Preludio_e_Fuga_6_in_Re_Minore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_847_0.Preludio_e_Fuga_2_in_Do_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_854.Preludio_e_Fuga_9_in_Mi_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_859.Preludio_e_Fuga_14_in_Fa_diesis_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_a.Preludio_e_Fuga_5_in_Re_Maggiore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_858.Preludio_e_Fuga_13_in_Fa_diesis_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_865.Preludio_e_Fuga_20_in_La_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_a.Preludio_e_Fuga_1_in_Do_Maggiore_(a).jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.BWV_846_0.Preludio_e_Fuga_1_in_Do_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.02.Fuga/Fuga_1_in_Do_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.01.1/§.01.Preludio/Preludio_1_in_Do_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_866.Preludio_e_Fuga_21_in_Sib_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_850_0.Preludio_e_Fuga_5_in_Re_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_856.Preludio_e_Fuga_11_in_Fa_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_855_0.Preludio_e_Fuga_10_in_Mi_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_857.Preludio_e_Fuga_12_in_Fa_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_852.Preludio_e_Fuga_7_in_Mib_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_851_0.Preludio_e_Fuga_6_in_Re_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_869.Preludio_e_Fuga_24_in_Si_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_862.Preludio_e_Fuga_17_in_Lab_Maggiore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_863.Preludio_e_Fuga_18_in_Lab_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_849.Preludio_e_Fuga_4_in_Do_diesis_Minore.jmxl/sheet.mxl",
	"./Bach/Il_Clavicembalo_Ben_Temperato/Libro_1/§.BWV_864.Preludio_e_Fuga_19_in_La_Maggiore.jmxl/sheet.mxl",
	"./Morceau_pour_contrebasse_et_d_accompaniment_violoncelle_MS3.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/007.Dotted_Notes.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/008.Repetition_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/028.Canon_at_the_Octave.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/035.Chorale.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/014.Question_and_Answer.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/006.Six_Unison_Melodies,_no._6.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/021.Four_Unison_Melodies,_no._4.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/004.Six_Unison_Melodies,_no._4.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/003.Six_Unison_Melodies,_no._3.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/005.Six_Unison_Melodies,_no._5.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/032.In_Dorian_Mode.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/002.Six_Unison_Melodies,_no._2.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/018.Four_Unison_Melodies,_no._1.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/031.Little_Dance_in_Canon_Form.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/025.Imitation_and_Inversion_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/026.Repetition_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/013.Change_of_Position.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/001.Six_Unison_Melodies,_no._1.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/023.Imitation_and_Inversion_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/012.Reflection.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/030.Canon_at_the_Lower_Fifth.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/015.Village_Song.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/027.Syncopation_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/017.Contrary_Motion_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/010.With_Alternate_Hands.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/020.Four_Unison_Melodies,_no._3.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/033.Slow_Dance.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/019.Four_Unison_Melodies,_no._2.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/009.Syncopation_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/024.Pastorale.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/036.Free_Canon.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/011.Parallel_Motion.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/034.In_Phrygian_Mode.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/029.Imitation_Reflected.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/016.Parallel_Motion_and_Change_of_Position.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_1/022.Imitation_and_Counterpoint.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/134.Studies_in_Double_Notes.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/128.Peasant_Dance.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/133.Syncopation_(3).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/138.Bagpipe.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/132.Major_Seconds_Broken_and_Together.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/126.Change_of_Time.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/130.Village_Joke.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/124.Staccato.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/136.Whole-tone_Scale.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/135.Perpetuum_mobile.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/139.Merry_Andrew.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/125.Boating.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/123.Staccato_and_Legato_(3).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/137.Unison.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/131.Fourths.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/129.Alternating_Thirds.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_5/122.Chords_Together_and_Opposed.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/147.March.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/152.Six_Dances_in_Bulgarian_Rhythm,_No._5.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/142.From_the_Diary_of_a_Fly.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/144.Minor_Seconds,_Major_Sevenths.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/143.Divided_Arpeggios.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/150.Six_Dances_in_Bulgarian_Rhythm,_No._3.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/148.Six_Dances_in_Bulgarian_Rhythm,_No._1.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/153.Six_Dances_in_Bulgarian_Rhythm,_No._6.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/149.Six_Dances_in_Bulgarian_Rhythm,_No._2.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/141.Subject_and_Reflection.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/145.Chromatic_Invention_(3).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/151.Six_Dances_in_Bulgarian_Rhythm,_No._4.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/140.Free_Variations.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_6/146.Ostinato.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/056.Melody_in_Tenths.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/062.Minor_Sixths_in_Parallel_Motion.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/060.Canon_with_Sustained_Notes.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/052.Monody_Divided.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/046.Increasing_-_Diminishing.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/057.Accents.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/050.Minuetto.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/054.Chromatic.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/040.In_Yugoslav_Style.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/059.Major_and_Minor.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/053.In_Transylvanian_Style.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/047.Big_Fair.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/049.Crescendo_-_Diminuendo.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/038.Staccato_and_Legato_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/045.Méditation.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/041.Melody_with_Accompaniment.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/048.In_Mixolydian_Mode.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/064.Line_and_Point.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/042.Accompaniment_in_Broken_Triads.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/051.Waves.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/063.Buzzing.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/061.Pentatonic_Melody.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/066.Melody_Divided.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/037.In_Lydian_Mode.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/058.In_Oriental_Style.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_2/039.Staccato_and_Legato_(2,_Canon).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/098.Thumb_Under.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/109.From_the_Island_of_Bali.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/100.In_the_Style_of_a_Folksong.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/120.Fifth_Chords.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/115.Bulgarian_Rhythm_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/106.Childrenʼs_Song.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/099.Crossed_Hands.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/114.Theme_and_Inversion.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/103.Minor_and_Major.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/105.Playsong_(with_two_pentatonic_scales).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/104.Wandering_through_the_Keys.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/108.Wrestling.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/116.Melody.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/121.Two-part_Study.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/107.Melody_in_the_Mist.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/110.Clashing_Sounds.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/119.Dance_in_3∕4_Time.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/113.Bulgarian_Rhythm_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/111.Intermezzo.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/097.Notturno.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/112.Variations_on_a_Folk_Tune.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/102.Harmonics.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/118.Triplets_in_9∕8_Time.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/117.Bourée.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_4/101.Diminished_Fifths.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/086.Two_Major_Pentachords.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/093.In_Four_Parts_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/073.Sixths_and_Triads.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/081.Wandering.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/091.Chromatic_Invention_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/080.Hommage_à_R._Sch..jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/078.Five-tone_Scale.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/077.Little_Study.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/087.Variations.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/076.In_Three_Parts.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/095.Song_of_the_Fox.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/075.Triplets.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/067.Thirds_against_a_Single_Voice.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/094.Tale.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/090.In_Russian_Style.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/096.Stumblings.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/088.Duet_for_Pipes.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/074.Hungarian_Song.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/083.Melody_with_Interruptions.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/082.Scherzo.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/079.Hommage_à_J._S._B..jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/085.Broken_Chords.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/072.Dragonsʼ_Dance.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/069.Chord_Study.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/089.In_Four_Parts_(1).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/084.Merriment.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/070.Melody_against_Double_Notes.jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/092.Chromatic_Invention_(2).jmxl/sheet.mxl",
	"./Bartók/Mikrokosmos/Volume_3/071.Thirds.jmxl/sheet.mxl",
];
sort($files);

function makeScore($dir, $order){
	$info = [
		"caption" => basename($dir,'.jmxl'),
		"order" => $order,
		"type" => "sheet",
		"sheet" => "sheet.mxl",
		"practice" => false,
		"shot" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
		"fail" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
		"done" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
	];
	$json = json_encode($info,JSON_PRETTY_PRINT);
	file_put_contents("${dir}/info.json",$json);
	echo "${json}\n";
}

function makeInfo($dir){
	$folders = glob("${dir}/*");
	$order = 1;
	$subOrder = 1;
	foreach($folders as $folder) {
		if (is_dir($folder)) {
			if ( !str_ends_with($folder,".jmxl") ) {
				makeInfo($folder);
			} else {
				makeScore($folder,$subOrder);
				$subOrder++;
			}
		}
		$order++;
	}
	$info = [
		"caption" => basename($dir),
		"order" => $order,
		"type" => "book",
		"sheet" => null,
		"practice" => false,
		"shot" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
		"fail" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
		"done" => [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],
	];
	$json = json_encode($info,JSON_PRETTY_PRINT);
	file_put_contents("${dir}/info.json",$json);
	echo "${json}\n";
}

makeInfo('.');